name: Bot Cron

on:
  schedule:
    - cron: "*/2 * * * *"   # каждые 2 минуты
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Call bot
        run: |
          curl "https://test-mini-ap-mk.vercel.app/api/cron/run?secret=123456"
