name: Bot Cron

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: curl "https://test-mini-ap-mk.vercel.app/api/cron/run?secret=bot_secret_2026_x9"
