name: Bot Cron

on:
  schedule:
    - cron: "*/5 * * * *" # каждые 5 минут
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Call bot
        run: |
          curl "https://test-mini-ap-mk.vercel.app/api/cron/run?secret=123456"
